services:
  bng-techspike-payment:
    build:
      context: .
      target: production
    image: bng-techspike-payment
    container_name: bng-techspike-payment
    environment:
      APPINSIGHTS_CLOUDROLE: bng-techspike-payment-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      PAYMENT_API_URL: https://publicapi.payments.service.gov.uk/v1/payments
      PAYMENT_API_KEY:
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies

