services:
  bng-techspike-payment:
    build:
      context: .
      target: production
    image: bng-techspike-payment
    container_name: bng-techspike-payment
    environment:
      APPINSIGHTS_CLOUDROLE: bng-techspike-payment-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
